export const TECH_STACK = [
  { name: "Adobe After Effects", icon: "adobeaftereffects", skillicon: "AfterEffects", color: "9999FF" },
  { name: "Adobe Illustrator", icon: "adobeillustrator", skillicon: "Illustrator", color: "FF9A00" },
  { name: "Adobe Photoshop", icon: "adobephotoshop", skillicon: "Photoshop", color: "31A8FF" },
  { name: "Adobe Premiere Pro", icon: "adobepremierepro", skillicon: "Premiere", color: "9999FF" },
  { name: "Alpine.js", icon: "alpinedotjs", skillicon: "AlpineJS", color: "8BC0D0" },
  { name: "Android", icon: "android", skillicon: "Android", color: "3DDC84" },
  { name: "Angular", icon: "angular", skillicon: "Angular", color: "DD0031" },
  { name: "Ansible", icon: "ansible", skillicon: "Ansible", color: "EE0000" },
  { name: "Apache Kafka", icon: "apachekafka", skillicon: "Kafka", color: "231F20" },
  { name: "Appwrite", icon: "appwrite", skillicon: "Appwrite", color: "FD366E" },
  { name: "Astro", icon: "astro", skillicon: "Astro", color: "FF5D01" },
  { name: "AWS", icon: "amazonaws", skillicon: "AWS", color: "232F3E" },
  { name: "Azure", icon: "microsoftazure", skillicon: "Azure", color: "0078D4" },
  { name: "Blender", icon: "blender", skillicon: "Blender", color: "F5792A" },
  { name: "Bun", icon: "bun", skillicon: "Bun", color: "000000" },
  { name: "C#", icon: "csharp", skillicon: "CS", color: "239120" },
  { name: "C++", icon: "cplusplus", skillicon: "CPP", color: "00599C" },
  { name: "Canva", icon: "canva", color: "00C4CC" },
  { name: "Clerk", icon: "clerk", color: "6C47FF" },
  { name: "Cypress", icon: "cypress", skillicon: "Cypress", color: "17202C" },
  { name: "Dart", icon: "dart", skillicon: "Dart", color: "0175C2" },
  { name: "Discord", icon: "discord", skillicon: "Discord", color: "5865F2" },
  { name: "Django", icon: "django", skillicon: "Django", color: "092E20" },
  { name: "Docker", icon: "docker", skillicon: "Docker", color: "2496ED" },
  { name: "Drizzle", icon: "drizzle", skillicon: "Drizzle", color: "C5F74F" },
  { name: "Elasticsearch", icon: "elasticsearch", skillicon: "Elasticsearch", color: "005571" },
  { name: "Ethereum", icon: "ethereum", skillicon: "Ethereum", color: "3C3C3D" },
  { name: "Ethers.js", icon: "ethers", skillicon: "EthersJS", color: "245AFA" },
  { name: "Expo", icon: "expo", skillicon: "Expo", color: "000020" },
  { name: "FastAPI", icon: "fastapi", skillicon: "FastAPI", color: "009688" },
  { name: "Figma", icon: "figma", skillicon: "Figma", color: "F24E1E" },
  { name: "Firebase", icon: "firebase", skillicon: "Firebase", color: "FFCA28" },
  { name: "Flask", icon: "flask", skillicon: "Flask", color: "000000" },
  { name: "Flutter", icon: "flutter", skillicon: "Flutter", color: "02569B" },
  { name: "Framer Motion", icon: "framer", skillicon: "Framer", color: "0055FF" },
  { name: "Git", icon: "git", skillicon: "Git", color: "F05032" },
  { name: "GitHub Actions", icon: "githubactions", skillicon: "GithubActions", color: "2088FF" },
  { name: "Go", icon: "go", skillicon: "Go", color: "00ADD8" },
  { name: "Google Cloud", icon: "googlecloud", skillicon: "GCP", color: "4285F4" },
  { name: "Grafana", icon: "grafana", skillicon: "Grafana", color: "F46800" },
  { name: "GraphQL", icon: "graphql", skillicon: "GraphQL", color: "E10098" },
  { name: "Heroku", icon: "heroku", skillicon: "Heroku", color: "430098" },
  { name: "Hono", icon: "hono", color: "E36002" },
  { name: "HTMX", icon: "htmx", skillicon: "HTMX", color: "3366CC" },
  { name: "Insomnia", icon: "insomnia", color: "4000BF" },
  { name: "iOS", icon: "ios", skillicon: "Apple", color: "000000" },
  { name: "Java", icon: "java", skillicon: "Java", color: "ED8B00" },
  { name: "JavaScript", icon: "javascript", skillicon: "JS", color: "F7DF1E" },
  { name: "Jest", icon: "jest", skillicon: "Jest", color: "C21325" },
  { name: "Jira", icon: "jira", skillicon: "Jira", color: "0052CC" },
  { name: "Kotlin", icon: "kotlin", skillicon: "Kotlin", color: "7F52FF" },
  { name: "Kubernetes", icon: "kubernetes", skillicon: "Kubernetes", color: "326CE5" },
  { name: "Laravel", icon: "laravel", skillicon: "Laravel", color: "FF2D20" },
  { name: "Linux", icon: "linux", skillicon: "Linux", color: "FCC624" },
  { name: "macOS", icon: "macos", skillicon: "Apple", color: "000000" },
  { name: "MongoDB", icon: "mongodb", skillicon: "MongoDB", color: "47A248" },
  { name: "MySQL", icon: "mysql", skillicon: "MySQL", color: "4479A1" },
  { name: "Netlify", icon: "netlify", skillicon: "Netlify", color: "00C7B7" },
  { name: "Next.js", icon: "nextdotjs", skillicon: "NextJS", color: "000000" },
  { name: "Nginx", icon: "nginx", skillicon: "Nginx", color: "009639" },
  { name: "Node.js", icon: "nodedotjs", skillicon: "NodeJS", color: "339933" },
  { name: "Notion", icon: "notion", skillicon: "Notion", color: "000000" },
  { name: "Nuxt.js", icon: "nuxtdotjs", skillicon: "NuxtJS", color: "00C58E" },
  { name: "OpenCV", icon: "opencv", skillicon: "OpenCV", color: "5C3EE8" },
  { name: "PHP", icon: "php", skillicon: "PHP", color: "777BB4" },
  { name: "Playwright", icon: "playwright", skillicon: "Playwright", color: "2EAD33" },
  { name: "PocketBase", icon: "pocketbase", skillicon: "PocketBase", color: "B8DBE4" },
  { name: "Postman", icon: "postman", skillicon: "Postman", color: "FF6C37" },
  { name: "PostgreSQL", icon: "postgresql", skillicon: "PostgreSQL", color: "4169E1" },
  { name: "Prisma", icon: "prisma", skillicon: "Prisma", color: "2D3748" },
  { name: "Prometheus", icon: "prometheus", skillicon: "Prometheus", color: "E6522C" },
  { name: "Python", icon: "python", skillicon: "Python", color: "3776AB" },
  { name: "PyTorch", icon: "pytorch", skillicon: "PyTorch", color: "EE4C2C" },
  { name: "RabbitMQ", icon: "rabbitmq", skillicon: "RabbitMQ", color: "FF6600" },
  { name: "React Query", icon: "reactquery", skillicon: "ReactQuery", color: "FF4154" },
  { name: "React Router", icon: "reactrouter", skillicon: "ReactRouter", color: "CA4245" },
  { name: "React Native", icon: "react", skillicon: "ReactNative", color: "61DAFB" },
  { name: "React", icon: "react", skillicon: "React", color: "61DAFB" },
  { name: "Redis", icon: "redis", skillicon: "Redis", color: "DC382D" },
  { name: "Redux", icon: "redux", skillicon: "Redux", color: "764ABC" },
  { name: "Remix", icon: "remix", skillicon: "Remix", color: "000000" },
  { name: "Ruby", icon: "ruby", skillicon: "Ruby", color: "CC342D" },
  { name: "Rust", icon: "rust", skillicon: "Rust", color: "000000" },
  { name: "Sanity", icon: "sanity", skillicon: "Sanity", color: "F03E2F" },
  { name: "Sass", icon: "sass", skillicon: "Sass", color: "CC6699" },
  { name: "Selenium", icon: "selenium", skillicon: "Selenium", color: "43B02A" },
  { name: "Shadcn/UI", icon: "shadcnui", skillicon: "Shadcn", color: "000000" },
  { name: "Slack", icon: "slack", skillicon: "Slack", color: "4A154B" },
  { name: "Solidity", icon: "solidity", skillicon: "Solidity", color: "363636" },
  { name: "SolidJS", icon: "solid", skillicon: "SolidJS", color: "2C4F7C" },
  { name: "Spring", icon: "spring", skillicon: "Spring", color: "6DB33F" },
  { name: "Strapi", icon: "strapi", color: "2E7EEA" },
  { name: "Stripe", icon: "stripe", skillicon: "Stripe", color: "008CDD" },
  { name: "Supabase", icon: "supabase", skillicon: "Supabase", color: "3ECF8E" },
  { name: "Svelte", icon: "svelte", skillicon: "Svelte", color: "FF3E00" },
  { name: "Swift", icon: "swift", skillicon: "Swift", color: "F05138" },
  { name: "Tailwind CSS", icon: "tailwindcss", skillicon: "Tailwind", color: "06B6D4" },
  { name: "TensorFlow", icon: "tensorflow", skillicon: "TensorFlow", color: "FF6F00" },
  { name: "Terraform", icon: "terraform", skillicon: "Terraform", color: "7B42BC" },
  { name: "Three.js", icon: "threedotjs", skillicon: "ThreeJS", color: "000000" },
  { name: "tRPC", icon: "trpc", skillicon: "TRPC", color: "2596BE" },
  { name: "Turbo", icon: "turborepo", skillicon: "Turborepo", color: "EF4444" },
  { name: "TypeScript", icon: "typescript", skillicon: "TS", color: "3178C6" },
  { name: "Unity", icon: "unity", skillicon: "Unity", color: "000000" },
  { name: "Unreal Engine", icon: "unrealengine", skillicon: "UnrealEngine", color: "0E1128" },
  { name: "Vercel", icon: "vercel", skillicon: "Vercel", color: "000000" },
  { name: "Vite", icon: "vite", skillicon: "Vite", color: "646CFF" },
  { name: "Vitest", icon: "vitest", skillicon: "Vitest", color: "6E9F18" },
  { name: "VS Code", icon: "visualstudiocode", skillicon: "VSCode", color: "007ACC" },
  { name: "Vue.js", icon: "vuedotjs", skillicon: "VueJS", color: "4FC08D" },
  { name: "Web3.js", icon: "web3dotjs", skillicon: "Web3JS", color: "F16822" },
  { name: "Windows", icon: "windows", skillicon: "Windows", color: "0078D6" },
  { name: "Zod", icon: "zod", skillicon: "Zod", color: "3E67B1" },
  { name: "Zustand", icon: "zustand", color: "433929" },
];

export const HOBBIES = [
  { name: "Coding", icon: "💻" },
  { name: "Gaming", icon: "🎮" },
  { name: "Reading", icon: "📚" },
  { name: "Music", icon: "🎵" },
  { name: "Photography", icon: "📷" },
  { name: "Traveling", icon: "✈️" },
  { name: "Cooking", icon: "🍳" },
  { name: "Sports", icon: "⚽" },
  { name: "Art", icon: "🎨" },
  { name: "Movies", icon: "🎬" },
  { name: "Writing", icon: "✍️" },
  { name: "Hiking", icon: "🥾" },
  { name: "Cycling", icon: "🚲" },
  { name: "Swimming", icon: "🏊" },
  { name: "Dancing", icon: "💃" },
];
